config/routes.rb
SSRails::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users

  scope "/bonfiretides" do
	  resources :users, :data_types
	end
end

app/models/data_type.rb
class DataType < ActiveRecord::Base
  has_many :items
  attr_accessible :description, :title
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :data_type
  attr_accessible :description, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/data_types_controller.rb
class DataTypesController < ApplicationController
  respond_to :html, :js, :json

  # GET /data_types
  # GET /data_types.json
  def index
    @types = DataType.all

    respond_with(@types)
  end

  # GET /data_types/1
  # GET /data_types/1.json
  def show
    @type = DataType.find(params[:id])

    respond_with(@type)
  end

  # GET /data_types/new
  # GET /data_types/new.json
  def new
    @type = DataType.new
    render :partial => 'form', :locals => {:type => @type}
  end

  # GET /data_types/1/edit
  def edit
    @type = DataType.find(params[:id])
  end

  # POST /data_types
  # POST /data_types.json
  def create
    @type = DataType.new(params[:data_type])

    respond_to do |format|
      if @type.save
        # respond_with(@type)
        # format.html { redirect_to @type, notice: 'Data type was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data_types/1
  # PUT /data_types/1.json
  def update
    @type = DataType.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:data_type])
        format.html { redirect_to @type, notice: 'Data type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_types/1
  # DELETE /data_types/1.json
  def destroy
    @type = DataType.find(params[:id])
    @id = params[:id]
    if @type.destroy
        respond_with(@id)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @type = DataType.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_types_helper.rb
module DataTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/data_types/_data_type.html.erb
<% type ||= @type %>

<tr id="type_<%= type.id %>">
    <td><%= type.title %></td>
    <td><%= type.description %></td>
    <td><%= link_to 'Edit', edit_data_type_path(type), :class => 'edit_band' %>
    	<%= link_to 'Destroy', type, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => 'delete' %>

</tr>

app/views/data_types/_form.html.erb
<%= simple_form_for @type, :remote => true do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title %>
  	<%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/data_types/_form.html.haml
.row.form
  = form_for type, :remote => true, :html => {:class => 'remote-form'} do |f|
    .column= f.text_field :title
    .column
      = f.submit
      = link_to 'Cancel', '#', :class => 'cancel'

app/views/data_types/create.js.erb
removeForm();
appendContent("<%= escape_javascript(render(@type)) %>");
$("#type_#{@type.id}").effect("highlight", {}, 3000);

app/views/data_types/edit.html.erb
<h1>Editing data_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', data_types_path %>

app/views/data_types/index.html.erb
<h1>Listing Data Types</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<%= render :partial => "data_type", :collection => @types, :as => :type %>
</table>

<br />

<%= link_to 'New Data type', new_data_type_path, :class => "new" %>

app/views/data_types/new.html.erb
<h1>New data_type</h1>

<%= render 'form' %>

<%= link_to 'Back', data_types_path %>

app/views/data_types/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @type.title %></h2>
<ul>
	<% @type.items.each do |item| %>
		<li><%= item.title %></li>
	<% end %>
</ul>

To put here:<br>
- What fields client sees when making a new <%= @type.title %>.<br>
- List of <%= @type.title %>'s (?)<br>
- ?

<p>
<%= link_to 'Edit', edit_data_type_path(@type) %> |
<%= link_to 'Back', data_types_path %>

app/views/home/index.html.erb
<h3>Home</h3>

The good stuff is <%= link_to "here", "/bonfiretides/data_types" %>.

app/views/items/_form.html.erb
<%= simple_form_for(@data_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title %>
  	<%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing data_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_type %> |
<%= link_to 'Back', data_types_path %>

app/views/items/index.html.erb
<h1>Listing Data Types</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<% @data_types.each do |data_type| %>
  <tr>
    <td><%= data_type.title %></td>
    <td><%= data_type.description %></td>
    <td><%= link_to 'Show', data_type %><br>
        <%= link_to 'Edit', edit_data_type_path(data_type) %><br>
        <%= link_to 'Destroy', data_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data type', new_data_type_path %>

app/views/items/new.html.erb
<h1>New data_type</h1>

<%= render 'form' %>

<%= link_to 'Back', data_types_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @data_type.title %></h2>
<ul>
	<% @data_type.items.each do |item| %>
		<li><%= item.title %></li>
	<% end %>
</ul>

To put here:<br>
- What fields client sees when making a new <%= @data_type.title %>.<br>
- List of <%= @data_type.title %>'s (?)<br>
- ?

<p>
<%= link_to 'Edit', edit_data_type_path(@data_type) %> |
<%= link_to 'Back', data_types_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Smoke Signals", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Smoke Signals" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ssrails" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>